Add Skyhook integration
mparticle-integrations/mparticle-apple-integration-skyhook pull request #1
Opened 2017-05-04 20:47 UTC by apavlov-skyhook

2017-05-09 20:40 UTC, peterjenkins requested changes
Can you please delete the copy of the skyhook SDK that's checked into this repo? (Since you are now sourcing it via CocoaPods.)

2017-05-10 02:40 UTC, apavlov-skyhook commented
Done, thank for noticing this.

2017-05-10 18:52 UTC, peterjenkins requested changes
@apavlov-skyhook Thanks for making that change.

Just had a couple more small changes but otherwise it's looking good.

1. Can you remove the extra pragmas / comments at the end of the .m file?
2. Can you squash the history into a single commit?

2017-05-11 01:32 UTC, apavlov-skyhook commented
Done.

2017-05-12 14:46 UTC, peterjenkins approved these changes
Looks good, thanks for making those changes.

2017-05-17 16:45 UTC, closed without merging

2017-05-17 17:58 UTC, peterjenkins commented
This is released as 6.14.0.